// file graphicalinterface.idl
module Graphics {
module corbaserver {

typedef double Transform [7];
typedef double Position [3];
typedef double Color [4];

  /// Corba exception travelling through the Corba channel
  interface Graphicalinterface {

       // set refreching rate of windows
       boolean setRate(in long rate);

       // refresh configurations
       void refresh();

       boolean createWindow(in string name);

       void getNodeList();
       void getWindowList();
       //void createWindow(in string name, in unsigned long x, in unsigned long y, in unsigned long width, in unsigned long height) ;

       boolean createScene(in string sceneName) ;
       boolean createSceneWithFloor(in string sceneName) ;
       boolean addSceneToWindow(in string sceneName, in string windowName) ;

       boolean addBox(in string boxName, in float boxSize1, in float boxSize2, in float boxSize3, in Color RGBAcolor) ;
       //boolean addBox(in string boxName, in float boxSize1, in float boxSize2, in float boxSize3) ;

       //boolean addCapsule(in string capsuleName, in float radius, in float height) ;
       boolean addCapsule(in string capsuleName, in float radius, in float height, in Color RGBAcolorid) ;

       boolean addMesh(in string meshName, in string meshPath) ;

       //boolean addCone(in string coneName, in float radius, in float height) ;
       boolean addCone(in string coneName, in float radius, in float height, in Color RGBAcolor) ;

       //boolean addCylinder(in string cylinderName, in float radius, in float height) ;
       boolean addCylinder(in string cylinderName, in float radius, in float height, in Color RGBAcolor) ;

       //boolean addSphere(in string sphereName, in float radius) ;
       boolean addSphere(in string sphereName, in float radius, in Color RGBAcolor) ;

       boolean addLine(in string lineName, in Position pos1, in Position pos2, in Color RGBAColor) ;

       boolean addURDF(in string urdfName, in string urdfPath, in string urdfPackage) ;

       boolean createGroup(in string groupName) ;
       boolean addToGroup(in string nodeName, in string groupName) ;

       boolean applyConfiguration(in string nodeName, in Transform configuration) ;

       boolean setVisibility(in string nodeName, in string visibilityMode) ;
       boolean setWireFrameMode(in string nodeName, in string wireFrameMode) ;
       boolean setLightingMode(in string nodeName, in string lightingMode) ;
  };
};
};
